### ISSUE TITLE
Django Forms Quiz

### ISSUE THREAD

**Issue by paujuanes** [csev/dj4e#14]
The question number 3 in "Quiz: Django Forms" seems to be impossible to get right.
It looks like a True/False question, but it has a text field to type the answer. Both true and false return "wrong answer".
Either there's a bug or it's confusingly written...

![image](https://user-images.githubusercontent.com/54763681/111779916-00475680-88b7-11eb-9dd1-6dba91aa5a18.png)

**Comment by paujuanes** [comment]
It's been fixed already :)

**Comment by csev** [comment]
Cool - thanks for the bug report.
