### ISSUE TITLE
404 file not found link sample image in https://www.dj4e.com/assn/dj4e_install.md

### ISSUE THREAD

**Issue by srcatto** [csev/dj4e#21]
Following instructions, 
https://www.dj4e.com/assn/dj4e_install.md
Running Your Application, at 

... never have to type "workon django3" and it makes sure your virtual envronment is properly set up and configured. Sample image

The "Sample image" links to, https://www.dj4e.com/assn/paw_install/web_tab.png and is the 404. 
Search dj4e for filename, new location is,
dj4e/assn/dj4e_local/web_tab.png

**Comment by csev** [comment]
Fixed.  Thanks.
