### ISSUE TITLE
Duplicate link

### ISSUE THREAD

**Issue by hottmannk** [csev/dj4e#30]
File: dj4e/lessons.json, lines: 164-171.

There is a duplicate link of "Setting up the django.org tutorial on PythonAnywhere" here.

https://www.dj4e.com/lessons/dj4e_install screenshot:
![link](https://user-images.githubusercontent.com/90543194/144757299-202d2c54-e4b7-4afe-81ad-1c4b9dde94bb.png)

**Comment by csev** [comment]
Catching up.  Thanks for this.
