### ISSUE TITLE
Unreasonable / Incorrect task assignment no. 13

### ISSUE THREAD

**Issue by Dorfieeee** [csev/dj4e#31]
Hi,

This issue is regarding assessment [Building and Loading a Data Model](https://github.com/csev/dj4e/blob/main/assn/dj4e_load.md) where I got absolutely confused when I was required to create 5 models for the given dataset. There is also discussion about it that others feel the same way.

_''In the Autograder instructions it says:_

_"This autograder checks the schemas and contents of the five tables (unesco_category, unesco_iso, unesco_region, unesco_site, and unesco_state) that will be created when the assignment is completed properly. "_

_When I have looked at the data, I also see 5 tables but not the ones above.  To me, it does not seem correct to have a separate table for the iso value.  Each state has its own unique iso ie each iso is associated with only one state, and each state is associated with only one iso.  In this respect, it seems to me that iso is a characteristic of the state and is a field in the state table.  There is no one-to-many relationship there and so it should not have its own table.''_ - **Michael Manning - 7 months ago**

Solution:
There should be only 4 Django models - Category, Region, State and Site

![13_github_fix](https://user-images.githubusercontent.com/65303812/146406326-5938c87c-7c33-44dd-ad72-876a05149aaf.jpg)

**Comment by csev** [comment]
The git repository is not the place to get help on the course.  But in your particular case, the model that the autograder is expecting is *as valid* as the model you are proposing.  Your model is encoding some constraints based on assumptions you ave made.  And your model is valid also.  A team would debate these things and could find their way clear to either model.  To keep the code simple the autograder expects five tables.
