### ISSUE TITLE
Bug in Peer Graded: Cascading Style Sheets (CSS) Assignment

### ISSUE THREAD

**Issue by pranabsarma18** [csev/dj4e#40]
When trying to access the "Assignment specification" link, it redirects back to the current page instead of directing to the intended assignment specification page.  This is the [assignment link](https://www.dj4e.com/lessons_launch/css)

https://github.com/csev/dj4e/assets/104676966/48c1a6d4-a68a-4916-8891-5728dc94e0db

**Comment by csev** [comment]
Thank you - this should now be fixed.
