### ISSUE TITLE
Quiz: CSS has question on JavaScript

### ISSUE THREAD

**Issue by pranabsarma18** [csev/dj4e#41]
I am not sure if it is intended but there is a question on JavaScript in this section [(link)](https://www.dj4e.com/lessons/css) which is not yet cover.

![image](https://github.com/csev/dj4e/assets/104676966/3c25ce82-6534-40c5-90b5-cf37ec7b7d2a)

**Comment by csev** [comment]
Thanks - this should now be fixed.
