### ISSUE TITLE
Autos CRUD Autograder bug

### ISSUE THREAD

**Issue by willthong** [csev/dj4e#44]
I believe there's a bug in the "Retrieving the Update page" element of the Autos CRUD Autograder. The grader is trying to resolve https://f860-172-58-111-218.ngrok-free.app9/update/ but I believe the right link should be https://f860-172-58-111-218.ngrok-free.app9/autos/lookup/27/update/ (or equivalent for a different primary key). The equivalent page on the sample, [https://crud.dj4e.com/update/](https://crud.dj4e.com/update/), similarly doesn't resolve.

![2023-06-15-231042_1118x472_scrot](https://github.com/csev/dj4e/assets/6254816/7689b8f0-792e-4923-939b-c767d4bc077a)

Thanks for this brilliant course!

**Comment by csev** [comment]
Don't the instructions tell you to include /autos in the url you submit to the autograder?  Going forward your Django project will get more and more projects (like autos and cats) so it pretty much ignores the "/" path.

**Comment by willthong** [comment]
Thanks Dr Chuck! Just what I needed - the autograder automatically finds the /autos and /cats subdomains, but this allowed me to find the problem. I double checked and your instructions included "main/" after the "autos" and "cats" parts of the URLs. I'd foolishly omitted these but when I added them back in the Autograder passed me. Thank you!
