### ISSUE TITLE
Classified Ad Site #2 Autograder bug

### ISSUE THREAD

**Issue by willthong** [csev/dj4e#45]
The Autograder is giving me an error: "Create Ad page appears to be missing JavaScript to check the size of the uploaded file".

However, my site is successfully rejecting using the JavaScript:

![2023-06-22-162935_700x498_scrot](https://github.com/csev/dj4e/assets/6254816/a14f26a6-cf72-4596-986a-9d50a0ccb1f1)

And the script appears in the source HTML:

![2023-06-22-163347_606x271_scrot](https://github.com/csev/dj4e/assets/6254816/b283c829-1265-48ae-b54b-80f88a686ff8)

Thanks for any help!

**Comment by csev** [comment]
This is not the place to get help in the course.   You need to start with the page that the auto grader is looking at when getting confused.  Sometimes the right UI is on the wrong URL.  Sometimes the autograder is looking for code that is identical to the sample code.  The autograder does not run your JavaScript - it merely looks at the source code of the page.
