### ISSUE TITLE
version of linux is not found

### ISSUE THREAD

**Issue by abdulshak1999** [csev/dj4e#9]
I'm one of your students and I'm using Linux, I don't want to use pythonerverywhere.com Instead I want to use either Ngrok or LocalTunnel

**Comment by csev** [comment]
This is the wrong place to ask for help.  There are localtunnel instructions at www.dj4e.com/lessons

**Comment by abdulshak1999** [comment]
> This is the wrong place to ask for help. There are localtunnel instructions at [www.dj4e.com/lessons](http://www.dj4e.com/lessons)

sorry for that
